### ISSUE TITLE
Fatal failure in cvc5::SolverEngine::getValue(const Node&) at src/smt/solver_engine.cpp:1024

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5-projects#404] opened 2022-01-14 21:48 UTC
cvc5/cvc5@0f5ee6bb4a
murxla/murxla@a0bac35
```
(set-option :global-declarations true)
(set-option :produce-models true)
(check-sat)
(get-value ((as set.universe (Set (Bag String) ) )))
```

error:

```
Fatal failure within cvc5::Node cvc5::SolverEngine::getValue(const Node&) const at src/smt/solver_engine.cpp:1024
Check failure

 m->hasApproximations() || resultNode.getKind() == kind::LAMBDA || resultNode.isConst()
```

**Comment by nafur** [comment] 2022-01-14 21:55
Is this another case where what I changed in #7951 should also return true for set values?

**Comment by ajreynol** [comment] 2022-01-14 22:18
No.

That assertion is simply too strict.  Basically it does not hold if you pass a term to `get-value` that cannot be evaluated.  I would suggest perhaps removing this assertion, since it was never expected to hold for anything except for simple SMT theories.

**Comment by ajreynol** [comment] 2022-02-04 14:28
Duplicate of https://github.com/cvc5/cvc5-projects/issues/401.

**Closed** 2022-02-04 14:28 UTC
Labels: murxla
