### ISSUE TITLE
Value of function term retrieved via getValue is not a model value.

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5-projects#355] opened 2021-11-17 02:43 UTC
cvc5/cvc5@cc4a58f5d43c62b72783d4bd1f4f00e6ef9257b4
murxla/murxla@cf030de8eb1ffca7cfd5137ab9802e4d7f5ad7dd

The following API trace (implemented as a unit test in `test/unit/api/cpp/solver_black.cpp`) retrieves the model value for a function term and checks if it is (which fails). 

```
TEST_F(TestApiBlackSolver, foo)                                                     
{                                                                                    
  d_solver.setLogic("HO_ALL");                                                       
  d_solver.setOption("incremental", "true");                                         
  d_solver.setOption("produce-unsat-assumptions", "true");                           
  d_solver.setOption("produce-models", "true");                                      
  Sort s1 = d_solver.getBooleanSort();                                               
  Sort s2 = d_solver.mkBagSort(s1);                                                  
  Term t2 = d_solver.mkConst(s2, "_x0");                                             
  Term t5 = d_solver.mkConst(s1, "_x3");                                             
  Term t83 = d_solver.mkTerm(BAG_COUNT, t5, t2);                                     
  Sort s6 = d_solver.mkFunctionSort(s1, t83.getSort());                              
  Term t164 = d_solver.mkConst(s6, "_x26");                                          
  d_solver.checkSat();                                                               
  Term v = d_solver.getValue(t164);                                                  
  ASSERT_TRUE (d_solver.checkSatAssuming(d_solver.mkTerm(EQUAL, t164, v)).isSat());     
}
```

**Comment by ajreynol** [comment] 2021-11-24 14:30
I think this is expected behavior. Can you check whether the checkSatAssuming is "unsat"?  I would actually expect the checkSatAssuming to return "unknown", as it is asserting a lambda.  We won't say "sat" for assertions with lambdas, unless `uf-lazy-ll` is enabled.

**Comment by aniemetz** [comment] 2021-11-29 18:19
The `checkSat()` result is `sat`.

**Comment by ajreynol** [comment] 2021-11-30 17:27
This line: `  ASSERT_TRUE (d_solver.checkSatAssuming(d_solver.mkTerm(EQUAL, t164, v)).isSat());  `  I think this is false since `unknown != sat`, right?

**Comment by ajreynol** [comment] 2022-03-14 20:13
I tested this. In general, you should test:
```
ASSERT_FALSE(d_solver.checkSatAssuming(d_solver.mkTerm(EQUAL, t164, v)).isUnsat());
```
not:
```
ASSERT_TRUE (d_solver.checkSatAssuming(d_solver.mkTerm(EQUAL, t164, v)).isSat());
```
to verify that a model is (not) wrong.  For higher-order, it is expected behavior that the solver could return "unknown" if you assert its model back to it.  Thus, closing this issue.

**Closed by ajreynol** 2022-03-14 20:13 UTC
Labels: more information needed, murxla
