### ISSUE TITLE
Assertion when non-value ends up in getValue

### ISSUE THREAD

**Issue by nafur** [cvc5/cvc5-projects#452] opened 2022-02-03 23:04 UTC
```
(reset)
(set-option :produce-models true)
(declare-const _x0 Real)
(define-sort _s0 (_y0 _y0) _y0)
(define-fun _f9 ((_f9_0 Real) (_f9_1 Real)) Real (/ 43066947547331242 _x0))
(check-sat)
(get-value ((let ((_let0 (_f9 _x0 _x0)))(> (* _let0 _let0) (/ 43066947547331242 _x0)))))
```
```
Fatal failure within cvc5::Node cvc5::SolverEngine::getValue(const Node&) const at /home/gereon/cvc5-master/src/smt/solver_engine.cpp:1025
Check failure

 m->hasApproximations() || TheoryModel::isValue(resultNode)
```

**Comment by nafur** [comment] 2022-02-03 23:11
A slightly simpler input:
```
(set-option :produce-models true)
(define-fun f ((x Real) (_f9_1 Real)) Real (/ 0 0.0))
(check-sat)
(get-value ((= 0.0 (f 0.0 0.0))))
```

**Comment by ajreynol** [comment] 2022-02-03 23:28
This is expected behavior, we should delete this assertion.

**Comment by ajreynol** [comment] 2022-02-04 14:28
Duplicate of Duplicate of https://github.com/cvc5/cvc5-projects/issues/401..

**Closed by ajreynol** 2022-02-04 14:28 UTC
Labels: murxla
