### ISSUE TITLE
Issue with CDHashMap

### ISSUE THREAD

**Issue by nafur** [cvc5/cvc5-projects#454] opened 2022-02-03 23:21 UTC
```
(set-option :global-declarations true)
(define-sort _s0 (_y1 _y1))
```
errors on a05b134c4 with:
```
Fatal failure within void cvc5::context::CDHashMap<Key, Data, HashFcn>::insertAtContextLevelZero(const Key&, const Data&) [with Key = std::__cxx11::basic_string<char>; Data = std::pair<std::vector<cvc5::api::Sort>, cvc5::api::Sort>; HashFcn = std::hash<std::__cxx11::basic_string<char> >] at /home/gereon/cvc5-master/src/./context/cdhashmap.h:408
Check failure

 d_map.find(k) == d_map.end()
```

**Comment by ajreynol** [comment] 2022-02-04 14:32
Duplicate of https://github.com/cvc5/cvc5-projects/issues/407.

**Closed by ajreynol** 2022-02-04 14:32 UTC
Labels: murxla
