### ISSUE TITLE
Fatal failure in NlModel::simpleCheckModelMsum() at src/theory/arith/nl/nl_model.cpp:895

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5-projects#376] opened 2021-12-03 21:10 UTC
cvc5/cvc5@cb4274dd5
murxla/murxla@6814683
```
(set-logic ALL)
(set-option :nl-ext light)
(assert (< real.pi 0.0))
(check-sat)
```

error:

```
Fatal failure within bool cvc5::theory::arith::nl::NlModel::simpleCheckModelMsum(const std::map<cvc5::NodeTemplate<true>, cvc5::NodeTemplate<true> >&, bool) at src/theory/arith/nl/nl_model.cpp:895
Check failure

 false
```

**Comment by ajreynol** [comment] 2022-01-13 19:42
I believe this is a duplicate of https://github.com/cvc5/cvc5/issues/4693.

**Closed** 2022-03-03 05:00 UTC
Labels: murxla
